import cv2
image = cv2.imread('circles.png')
grayImage = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
# returnValue,thresh = cv2.threshold(grayImage,120,255,0)
# cv2.imshow("shapes",grayImage)
# import pdb; pdb.set_trace()
canny = cv2.Canny(grayImage,127,255)
# cv2.imshow("shapes",canny)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
contours, hierarchy = cv2.findContours(canny,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
print(len(contours))
cv2.drawContours(image,contours,-1,(255, 0, 0),3)
# # import pdb; pdb.set_trace()
cv2.imshow("shapes",image)
cv2.waitKey(0)
cv2.destroyAllWindows()